version: "2.1"

services:

  flask:
    build: ./blog-src
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskBlog
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
