# Generated by Django 3.1.2 on 2020-10-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('pub_date', models.DateField(null=True, verbose_name='发布日期')),
                ('read', models.IntegerField(default=0, verbose_name='阅读量')),
                ('comment', models.IntegerField(default=0, verbose_name='评论量')),
                ('image', models.ImageField(null=True, upload_to='books', verbose_name='图片')),
            ],
        ),
    ]
