version: "3.8"

services:
  django:
    build: .
    container_name: django_expenses
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - Django_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A celery_tasks.main worker --loglevel=INFO
    volumes:
      - .:/src
    depends_on:
      - django
      - redis

  redis:
    image: "redis:alpine"
